networks:
  flare:
    rpc: https://rpc.ankr.com/flare
    chain-id: 14
    currency: FLR
  base:
    rpc: https://mainnet.base.org
    chain-id: 8453
    network-id: 8453
    currency: ETH
  sepolia:
    rpc: https://1rpc.io/sepolia
    chain-id: 11155111
    network-id: 11155111
    currency: ETH

subgraphs:
  flare: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-flare/0.2/gn
  base: http://replaceme.com
  sepolia: http://replaceme.com

metaboards:
  flare: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-flare-0x893BBFB7/0.1/gn
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-base-0x59401C93/0.1/gn
  sepolia: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-sepolia-0x77991674/0.1/gn

orderbooks:
  flare:
    address: 0xCEe8Cd002F151A536394E564b84076c41bBBcD4d
    network: flare
    subgraph: flare
  base:
    address: 0x80DE00e3cA96AE0569426A1bb1Ae22CD4181dE6F
    network: base
    subgraph: base
  sepolia:
    address: 0x0bB72B4C7c0d47b2CaED07c804D9243C1B8a0728
    network: sepolia
    subgraph: sepolia

deployers:
  flare:
    address: 0xE3989Ea7486c0F418C764e6c511e86f6E8830FAb
    network: flare
  base:
    address: 0xC1A14cE2fd58A3A2f99deCb8eDd866204eE07f8D
    network: base
  sepolia:
    address: 0x7692BA8446Bb8B3140A2c02df073080BeD0a7F8E
    network: sepolia