networks:
  flare:
    rpc: https://rpc.ankr.com/flare	
    chain-id: 14
    currency: FLR
  base: 
    rpc: https://mainnet.base.org	
    chain-id: 8453 
    network-id: 8453 
    currency: ETH
  sepolia: 
    rpc: https://1rpc.io/sepolia
    chain-id: 11155111 
    network-id: 11155111 
    currency: ETH
  polygon: 
    rpc: https://1rpc.io/polygon
    chain-id: 137 
    network-id: 137 
    currency: POL
  arbitrum: 
    rpc: https://rpc.ankr.com/arbitrum
    chain-id: 42161 
    network-id: 42161 
    currency: ETH
  matchain: 
    rpc: https://rpc.matchain.io
    chain-id: 698 
    network-id: 698 
    currency: BNB
  bsc: 
    rpc: https://rpc.ankr.com/bsc
    chain-id: 56 
    network-id: 56 
    currency: BNB

subgraphs:
  flare: http://replaceme.com
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-base/0.7/gn
  sepolia: http://replaceme.com
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-polygon/0.4/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-arbitrum/0.1/gn
  matchain: http://subgraph.mobula.io:8000/subgraphs/name/matchain-ob
  bsc: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-bsc/0.1/gn

metaboards:
  flare: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-flare-0x893BBFB7/0.1/gn
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-base-0x59401C93/0.1/gn
  sepolia: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-sepolia-0x77991674/0.1/gn
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-polygon/0.1/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-arbitrum/0.1/gn
  bsc: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-bsc/0.1/gn

orderbooks:
  flare:
    address: 0xaa3b14Af0e29E3854E4148f43321C4410db002bC
    network: flare
    subgraph: flare
  base:
    address: 0xd2938e7c9fe3597f78832ce780feb61945c377d7
    network: base
    subgraph: base
  sepolia:
    address: 0x0bB72B4C7c0d47b2CaED07c804D9243C1B8a0728
    network: sepolia
    subgraph: sepolia
  polygon:
    address: 0x7D2f700b1f6FD75734824EA4578960747bdF269A
    network: polygon
    subgraph: polygon
  arbitrum:
    address: 0x550878091b2B1506069F61ae59e3A5484Bca9166
    network: arbitrum
    subgraph: arbitrum
  matchain: 
    address: 0x40312edab8fe65091354172ad79e9459f21094e2
    network: matchain
    subgraph: matchain
  bsc: 
    address: 0xd2938E7c9fe3597F78832CE780Feb61945c377d7
    network: bsc
    subgraph: bsc
  
deployers:
  flare:
    address: 0x3214CdB105a73f8356583eCd85264cCfA8417694
    network: flare
  base:
    address: 0xC1A14cE2fd58A3A2f99deCb8eDd866204eE07f8D
    network: base
  sepolia:
    address: 0x7692BA8446Bb8B3140A2c02df073080BeD0a7F8E
    network: sepolia
  polygon:
    address: 0x7ff6688157639BE7B7f216025667248Fa2711d18
    network: polygon
  arbitrum:
    address: 0x9B0D254bd858208074De3d2DaF5af11b3D2F377F
    network: arbitrum
  matchain:
    address: 0x582d9e838FE6cD9F8147C66A8f56A3FBE513a6A2
    network: polygon
  bsc:
    address: 
    network: bsc
