networks:
  flare:
    rpc: https://rpc.ankr.com/flare	
    chain-id: 14
    currency: FLR

subgraphs:
  flare: http://replaceme.com
  
orderbooks:
  flare:
    address: 0xaa3b14Af0e29E3854E4148f43321C4410db002bC
    network: flare
    subgraph: flare
  
deployers:
  flare:
    address: 0xEBe394cff4980992B826Ec70ef0a9ec8b5D4C640
    network: flare